server:
  port: 8080

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    client:
      serviceUrl:
        defaultZone: http://eureka:8761/eureka/

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG

spring:
  application:
    name: zuul
  cloud:
    config:
      enabled: false
